version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - ./docker_volumes/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # 👈 mount host Docker socket
      - /usr/bin/docker:/usr/bin/docker             # 👈 mount docker client binary
